name = "b-nova"
license = "MIT"
licenselink = "https://github.com/gethinode/hinode/blob/main/LICENSE"
description = "A clean documentation and blog theme for your Hugo site based on Bootstrap 5."
homepage = "https://gethinode.com"
demosite = "https://demo.gethinode.com"
tags = ["blog", "documentation", "minimal", "modern", "customizable", "search", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts"]
min_version = "0.81.0"

[author]
  name = "Raffael
  homepage = "https://github.com/markdumay"