# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: List
  description: List section
  icon: post
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    preheading:
    heading:
    content:
    align:
    width:
  hide_empty:
  input:
    section:
    nested:
    keywords:
    categories:
    tags:
    reverse:
    sort:
  hook:
  limit:
  background:
    backdrop:
    color:
    subtle:
  cover:
  class:
  width:
  justify:
  theme:
  sortable:
  paginate:
  pagination:
  pagination_select:
  searchable:
  wrap:
