# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Approach
  description: Approach section
  icon: step
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    preheading:
    heading:
    content:
    align:
    width:
  cols:
  icon_rounded:
  icon_style:
  link_type:
  padding:
  background:
    backdrop:
    color:
    subtle:
  illustration:
    image:
    icon:
    ratio:
    class:
    anchor:
    mode:
  elements:
    - title:
      icon:
      image:
      mode:
      content:
      link:
  orientation:
  class:
  width:
  justify:
  align:
  fluid:
  theme:
  cover:
