# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: CTA
  description: Call to action
  icon: contact_page
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    preheading:
    title:
    content:
    align:
    arrangement:
    width:
    size:
  contact:
  caption-url:
  illustration:
    image:
    icon:
    ratio:
    class:
    anchor:
    mode:
  background:
    backdrop:
    color:
    subtle:
  links:
    -
      title:
      url:
      icon:
      force:
  align:
  fluid:
  padding:
  order:
  width:
  theme:
  cover:
