# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Video
  description: Video section
  icon: build
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    preheading:
    title:
    content:
    align:
    arrangement:
    width:
    size:
  background:
    backdrop:
    color:
    subtle:
  link_type:
  orientation:
  icon_rounded:
  icon_style:
  video:
    provider:
    account:
    media_id:
    autoplay:
    query_args:
    color:
  cols:
  messages:
    - title:
      icon:
      content:
      link:
      label:
  border:
  width:
  justify:
  fluid:
  theme:
  cover:

_structures:
  messages:
    values:
      value:
        title:
        icon:
        content:
        link:
        label:
