# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Menu
  description: Index of menu items
  icon: menu
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    preheading:
    heading:
    content:
    align:
    width:
  cols:
  menu:
  menu-style:
  icon-rounded: false
  icon-style:
  background:
    backdrop:
    color:
    subtle:
  class:
  width:
  justify:
  fluid:
  theme:
  cover:
