# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Testimonials
  description: Testimonials section
  icon: build
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background:
    color:
    subtle:
  card:
    color:
    subtle:
  icon_style:
  testimonials:
    - logo:
      icon:
      scale:
      content:
      client:
        name:
        url:
        image:
        mode:
      link:
  carousel:
  cols:
