# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Benefits
  description: Introduction section
  icon: check
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    preheading:
    heading:
    content:
    align:
    width:
  cols:
  icon-rounded:
  icon-style:
  padding:
  background:
    backdrop:
    color:
    subtle:
  elements:
    - title:
      icon:
      image:
      mode:
      content:
  orientation:
  class:
  width:
  justify:
  align:
  theme:
  cover:
