# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Teams
  description: Teams section
  icon: groups
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    preheading:
    heading:
    content:
    align:
    width:
  hide_empty:
  input:
    section:
    nested:
    keywords:
    categories:
    tags:
    reverse:
    sort:
  more:
    title:
    link:
    link_type:
    icon:
  cols:
  padding:
  limit:
  pagination:
  paginate:
  background:
    backdrop:
    color:
    subtle:
  cover:
  header_style:
  body_style:
  footer_style:
  orientation:
  class:
  width:
  justify:
  fluid:
  theme:
