# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Featured
  description: Featured section
  icon: mode_heat
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    preheading:
    title:
    content:
    align:
    arrangement:
    width:
    size:
  background:
    backdrop:
    color:
    subtle:
  illustration:
    image:
    icon:
    ratio:
    class:
    anchor:
    mode:
  order:
  width:
  justify:
  link-type:
  fluid:
  theme:
  cover:
  links:
    -
      title:
      url:
      download:
      icon:
      force:
