name: Lint & build
on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches: [ main, beta ]
  pull_request:
    branches: [ main, beta ]

permissions:
  pull-requests: read
  contents: read

jobs:
  lint-build:
    uses: gethinode/.github/.github/workflows/lint-build.yml@test/no-hoisted
    with:
      package-manager: pnpm
      lint-script: lint
      build-command: pnpm run build:cache && pnpm run build:example:ci
      cache-key: hugo-hinode
      dart-sass-version: "1.98.0"
    secrets: inherit
