name: npm compatibility
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"
jobs:
  npm-compat:
    uses: gethinode/.github/.github/workflows/npm-compat.yml@v1
    with:
      build-script: build:example
