name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta

jobs:
  audit:
    name: Audit dependencies for known vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Audit dependencies for known vulnerabilities
        run: pnpm audit --prod --audit-level=high

  release:
    needs: audit
    uses: gethinode/.github/.github/workflows/release.yml@v1
    with:
      package-manager: pnpm
    secrets: inherit
