name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    uses: gethinode/.github/.github/workflows/release.yml@v1
    with:
      package-manager: pnpm
    secrets: inherit
